/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as LoadingDemoRouteImport } from "./pages/loading-demo"
import { Route as R500RouteImport } from "./pages/500"
import { Route as R404RouteImport } from "./pages/404"
import { Route as IndexRouteImport } from "./pages/index"

const LoadingDemoRoute = LoadingDemoRouteImport.update({
  id: "/loading-demo",
  path: "/loading-demo",
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: "/500",
  path: "/500",
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/loading-demo": typeof LoadingDemoRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/loading-demo": typeof LoadingDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/loading-demo": typeof LoadingDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/404" | "/500" | "/loading-demo"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/404" | "/500" | "/loading-demo"
  id: "__root__" | "/" | "/404" | "/500" | "/loading-demo"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  LoadingDemoRoute: typeof LoadingDemoRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/loading-demo": {
      id: "/loading-demo"
      path: "/loading-demo"
      fullPath: "/loading-demo"
      preLoaderRoute: typeof LoadingDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/500": {
      id: "/500"
      path: "/500"
      fullPath: "/500"
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  R500Route: R500Route,
  LoadingDemoRoute: LoadingDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
